[package]
name = "monkeytype"
version = "0.2.0"
description = "Monkeytype Desktop"
authors = ["you"]
edition = "2021"

[[bin]]
name = "Monkeytype"
path = "src/main.rs"

[lib]
name = "monkeytype_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
